name: LWCTrust
main: com.fantasycraft.lwcmodules.FantasyCraftPlugin
version: 1.1
depend: [LWC, Towny]
commands:
    trust:
        permission: fantasycraft.trust
    untrust:
        permission: fantasycraft.trust
    trustlist:
        permission: fantasycraft.trust